// Jenkins Token: 1167f6078ed075c9a00163ecad37641c12
pipeline {
    agent any
    stages {
        stage('Create and Deploy IaC') {
            steps {
                script {
                    // Execute SSH command and wait for completion
                    sshagent(['ssh-agent']) {
                        def sshResult = sh(script: """
                            ssh -o StrictHostKeyChecking=no ubuntu@54.72.122.253 '
                                echo "Hello From Riyad" > file.txt '
                            """, returnStatus: true)
                        if (sshResult != 0) {
                            error "SSH connection failed"
                        }
                    }
                }
            }
        }   
    }
}
