name: Pull GitHub Repository Contents and Deploy to Jenkins

on:
  push:
    branches: [main] 

jobs:
  pull_repo_and_deploy:
    name: Pull GitHub Repository Contents and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image
        run: docker build -t riyadm44/djangonewsimage:latest .

      - name: Push Docker image
        run: docker push riyadm44/djangonewsimage:latest

      - name: Create SSH directory
        run: mkdir -p ~/.ssh

      - name: Write private key to file
        run: echo "${{ secrets.KEY }}" > ~/.ssh/Riyad_PaloAlto_Key.pem

      - name: Set permissions for private key file
        run: chmod 600 ~/.ssh/Riyad_PaloAlto_Key.pem

      - name: Update known_hosts file
        run: ssh-keyscan -H 52.30.120.87 >> ~/.ssh/known_hosts

      - name: Execute commands on remote server
        run: |
          ssh -i ~/.ssh/Riyad_PaloAlto_Key.pem ubuntu@52.30.120.87 '
          if ! command -v docker &> /dev/null
            then
                sudo apt-get update
                sudo apt-get install -y \
                    ca-certificates \
                    curl \
                    gnupg \
                    lsb-release
                sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
                echo \
                  "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
                  $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
                sudo apt-get update
                sudo apt-get install -y docker-ce docker-ce-cli containerd.io
                sudo chmod 666 /var/run/docker.sock 
          fi
          docker stop ry || true &&
          docker rm ry || true &&
          docker rmi riyadm44/djangonewsimage || true &&
          docker pull riyadm44/djangonewsimage:latest &&                                
          docker run -d -p 8000:8000 --name ry riyadm44/djangonewsimage '
          