name: Pull GitHub Repository Contents and Deploy to Jenkins

on:
  push:
    branches: [main]

jobs:
  pull_repo_and_deploy:
    name: Pull GitHub Repository Contents and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image
        run: docker build -t riyadm44/djangonewsimage:latest .

      - name: Push Docker image
        run: docker push riyadm44/djangonewsimage:latest

      - name: Trigger Jenkins Pipeline
        run: |
          curl -X POST \
            -u RY:1167f6078ed075c9a00163ecad37641c12 \
            -d '' \
            http://54.72.122.253:8080/job/RY/build